#!/bin/sh
# python ../initialRetrieve.py -b Dance
# python ../initialRetrieve.py -b Database
# python ../initialRetrieve.py -b DataSciences
# python ../initialRetrieve.py -b Detective
# python ../initialRetrieve.py -b DHU
# python ../initialRetrieve.py -b Donation
# python ../initialRetrieve.py -b DotNet
# python ../initialRetrieve.py -b Dreamer
# python ../initialRetrieve.py -b DUT
# python ../initialRetrieve.py -b DVD
# python ../initialRetrieve.py -b E-Sports
# python ../initialRetrieve.py -b EB23
# python ../initialRetrieve.py -b ebiz
# python ../initialRetrieve.py -b ECNU
# python ../initialRetrieve.py -b Economics
# python ../initialRetrieve.py -b ECUST
# python ../initialRetrieve.py -b Education
# python ../initialRetrieve.py -b EE
# python ../initialRetrieve.py -b EmergingNetworking
# python ../initialRetrieve.py -b Engineering
# python ../initialRetrieve.py -b EnglishChat
# python ../initialRetrieve.py -b Environmental
# python ../initialRetrieve.py -b Europe
# python ../initialRetrieve.py -b EuropeNews
# python ../initialRetrieve.py -b Exchange
# python ../initialRetrieve.py -b Faculty
# python ../initialRetrieve.py -b Family
# python ../initialRetrieve.py -b Fashion
# python ../initialRetrieve.py -b FDU
# python ../initialRetrieve.py -b Fengshui
# python ../initialRetrieve.py -b FieldHockey
# python ../initialRetrieve.py -b Fishing
# python ../initialRetrieve.py -b Fitness
# python ../initialRetrieve.py -b Flash
# python ../initialRetrieve.py -b FleaMarket
# python ../initialRetrieve.py -b Florida
# python ../initialRetrieve.py -b Food
# python ../initialRetrieve.py -b Football
# python ../initialRetrieve.py -b Fujian
# python ../initialRetrieve.py -b fyzlaw
# python ../initialRetrieve.py -b Gamble
# python ../initialRetrieve.py -b Game
# python ../initialRetrieve.py -b gardening
# python ../initialRetrieve.py -b GenderEquality
# python ../initialRetrieve.py -b Georgia
# python ../initialRetrieve.py -b GeoSpace
# python ../initialRetrieve.py -b Germany
# python ../initialRetrieve.py -b Ghost
# python ../initialRetrieve.py -b GiftCard
# python ../initialRetrieve.py -b Girl
# python ../initialRetrieve.py -b Go
# python ../initialRetrieve.py -b Golf
# python ../initialRetrieve.py -b Gowest
# python ../initialRetrieve.py -b GreatPit
# python ../initialRetrieve.py -b Guang_Xi
# python ../initialRetrieve.py -b GunsAndGears