#!/bin/sh
 python ../updateboard.py -b AC
 python ../updateboard.py -b Accounting
 python ../updateboard.py -b Actuary
 python ../updateboard.py -b AHU
 python ../updateboard.py -b Alabama
 python ../updateboard.py -b Anhui
 python ../updateboard.py -b Animals
 python ../updateboard.py -b Anniversary
 python ../updateboard.py -b Announcement
 python ../updateboard.py -b AnthroLing
 python ../updateboard.py -b Apple
 python ../updateboard.py -b ApplyClub
 python ../updateboard.py -b Archery
 python ../updateboard.py -b Arizona
 python ../updateboard.py -b ARKANSAS
 python ../updateboard.py -b Arts
 python ../updateboard.py -b AsiaNews
 python ../updateboard.py -b astrology
 python ../updateboard.py -b Astronomy
 python ../updateboard.py -b AudioBook
 python ../updateboard.py -b Australia
 python ../updateboard.py -b AustraliaNews
 python ../updateboard.py -b Automobile
 python ../updateboard.py -b Avatar
 python ../updateboard.py -b Aviation
 python ../updateboard.py -b BackHome
 python ../updateboard.py -b Badminton
 python ../updateboard.py -b bagua
 python ../updateboard.py -b Banquet
 python ../updateboard.py -b Baseball
 python ../updateboard.py -b Basketball
 python ../updateboard.py -b BBI
 python ../updateboard.py -b Beijing
 python ../updateboard.py -b Belief
 python ../updateboard.py -b Berkeley
 python ../updateboard.py -b Billiards
 python ../updateboard.py -b Biology
 python ../updateboard.py -b BIT
 python ../updateboard.py -b BJTU
 python ../updateboard.py -b BJUT
 python ../updateboard.py -b Blessing
 python ../updateboard.py -b BMU
 python ../updateboard.py -b BNU
 python ../updateboard.py -b board
 python ../updateboard.py -b Boston
 python ../updateboard.py -b BrainTeaser
 python ../updateboard.py -b BrainTrust
 python ../updateboard.py -b Bridge
 python ../updateboard.py -b BUAA
 python ../updateboard.py -b BUCT
 python ../updateboard.py -b BuildingWeb
 python ../updateboard.py -b BUPT
 python ../updateboard.py -b Business
 python ../updateboard.py -b BusinessNews
 python ../updateboard.py -b Canada
 python ../updateboard.py -b CanadaNews
 python ../updateboard.py -b Cantonese
 python ../updateboard.py -b Carolinas
 python ../updateboard.py -b CAU
 python ../updateboard.py -b ChemEng
 python ../updateboard.py -b Chemistry
 python ../updateboard.py -b ChenLaw
 python ../updateboard.py -b Chess
 python ../updateboard.py -b Chicago
 python ../updateboard.py -b China
 python ../updateboard.py -b ChinaNews
 python ../updateboard.py -b ChinaNews2
 python ../updateboard.py -b ChinaStock
 python ../updateboard.py -b Chinese
 python ../updateboard.py -b ChineseClassics
 python ../updateboard.py -b ChineseMed
 python ../updateboard.py -b Chongqing
 python ../updateboard.py -b ChuanYu
 python ../updateboard.py -b CivilEngineering
 python ../updateboard.py -b CivilSociety
 python ../updateboard.py -b ClassicalMusic
 python ../updateboard.py -b Classified
 python ../updateboard.py -b Collectibles
 python ../updateboard.py -b Collection
 python ../updateboard.py -b Colorado
 python ../updateboard.py -b Comic
 python ../updateboard.py -b Complain
 python ../updateboard.py -b Computation
 python ../updateboard.py -b ComputerGraphics
 python ../updateboard.py -b Connecticut
 python ../updateboard.py -b CouchPotato
 python ../updateboard.py -b CQU
 python ../updateboard.py -b Craft
 python ../updateboard.py -b CS
 python ../updateboard.py -b CSU
 python ../updateboard.py -b CUPL
 python ../updateboard.py -b Cycling