#!/bin/sh
python ../updateboard.py -b HAINAN
python ../updateboard.py -b Hardware
python ../updateboard.py -b Hawaii
python ../updateboard.py -b Headline
python ../updateboard.py -b Heart
python ../updateboard.py -b Hebei
python ../updateboard.py -b Henan
python ../updateboard.py -b HiFi
python ../updateboard.py -b History
python ../updateboard.py -b HIT
python ../updateboard.py -b HKUST
python ../updateboard.py -b HNU
python ../updateboard.py -b Hockey
python ../updateboard.py -b HongKong
python ../updateboard.py -b hooyou
python ../updateboard.py -b HouseRental
python ../updateboard.py -b Hubei
python ../updateboard.py -b HuNan
python ../updateboard.py -b HuNaUuniversity
python ../updateboard.py -b HUST
python ../updateboard.py -b I140
python ../updateboard.py -b I485
python ../updateboard.py -b IDAHO
python ../updateboard.py -b Immigration
python ../updateboard.py -b ImmigrationNews
python ../updateboard.py -b Indiana
python ../updateboard.py -b InnerMongolia
python ../updateboard.py -b Internet
python ../updateboard.py -b Investment
python ../updateboard.py -b Iowa
python ../updateboard.py -b iShow
python ../updateboard.py -b Japan
python ../updateboard.py -b Java
python ../updateboard.py -b Jiangnan
python ../updateboard.py -b Jiangsu
python ../updateboard.py -b Jiangxi
python ../updateboard.py -b jingchenglaw
python ../updateboard.py -b JLU
python ../updateboard.py -b JobHunting
python ../updateboard.py -b JobMarket
python ../updateboard.py -b Joke
python ../updateboard.py -b Kansas
python ../updateboard.py -b Kentucky
python ../updateboard.py -b Korea
python ../updateboard.py -b Law
python ../updateboard.py -b LeisureTime
python ../updateboard.py -b LES
python ../updateboard.py -b Linux
python ../updateboard.py -b Literature
python ../updateboard.py -b LiuLaw
python ../updateboard.py -b Living
python ../updateboard.py -b LocalInfo
python ../updateboard.py -b LosAngeles
python ../updateboard.py -b loseweight
python ../updateboard.py -b Louisiana
python ../updateboard.py -b Love
python ../updateboard.py -b LoveNLust
python ../updateboard.py -b LZU