#!/bin/sh
python ../updateboard.py -b UESTC
python ../updateboard.py -b UMD
python ../updateboard.py -b UnitedKingdom
python ../updateboard.py -b Unix
python ../updateboard.py -b USANews
python ../updateboard.py -b USTB
python ../updateboard.py -b USTC
python ../updateboard.py -b Utah
python ../updateboard.py -b Vancouver
python ../updateboard.py -b Virginia
python ../updateboard.py -b Visa
python ../updateboard.py -b VolleyBall
python ../updateboard.py -b vote
python ../updateboard.py -b WashingtonDC
python ../updateboard.py -b Watch
python ../updateboard.py -b WaterWorld
python ../updateboard.py -b WBCenter
python ../updateboard.py -b WebRadio
python ../updateboard.py -b WeddingBells
python ../updateboard.py -b WeGreened
python ../updateboard.py -b Weightlifting
python ../updateboard.py -b Whisper
python ../updateboard.py -b WHU
python ../updateboard.py -b Windows
python ../updateboard.py -b Wisconsin
python ../updateboard.py -b Wisdom
python ../updateboard.py -b WmGame
python ../updateboard.py -b Working
python ../updateboard.py -b WorldNews
python ../updateboard.py -b Xibei
python ../updateboard.py -b XiDian
python ../updateboard.py -b XieLaw
python ../updateboard.py -b Xiqu
python ../updateboard.py -b XJTU
python ../updateboard.py -b XML
python ../updateboard.py -b XMU
python ../updateboard.py -b yanglaw
python ../updateboard.py -b yoga
python ../updateboard.py -b Zhejiang
python ../updateboard.py -b ZJU
python ../updateboard.py -b ZSU
python ../updateboard.py -b Zumba