#!/bin/sh
python ../updateboard.py -b QDU
python ../updateboard.py -b QiGong
python ../updateboard.py -b Quant
python ../updateboard.py -b QueerNews
python ../updateboard.py -b Racing
python ../updateboard.py -b Rainbow
python ../updateboard.py -b Reader
python ../updateboard.py -b Recommend
python ../updateboard.py -b RegulatoryAffairs
python ../updateboard.py -b Returnee
python ../updateboard.py -b Reunion
python ../updateboard.py -b RhodeIsland
python ../updateboard.py -b RisingChina
python ../updateboard.py -b Rock
python ../updateboard.py -b RUC
python ../updateboard.py -b Running
python ../updateboard.py -b RuralChina
python ../updateboard.py -b Salon
python ../updateboard.py -b SanDiego
python ../updateboard.py -b SanFrancisco
python ../updateboard.py -b Science
python ../updateboard.py -b SciFiction
python ../updateboard.py -b ScitechNews
python ../updateboard.py -b SCU
python ../updateboard.py -b SCUT
python ../updateboard.py -b SDU
python ../updateboard.py -b Seattle
python ../updateboard.py -b Security
python ../updateboard.py -b SellAbroad
python ../updateboard.py -b SEU
python ../updateboard.py -b Sex
python ../updateboard.py -b Sex2
python ../updateboard.py -b Shaanxi
python ../updateboard.py -b Shandong
python ../updateboard.py -b Shanghai
python ../updateboard.py -b Shanxi
python ../updateboard.py -b shopping
python ../updateboard.py -b Singapore
python ../updateboard.py -b single
python ../updateboard.py -b SJTU
python ../updateboard.py -b Ski
python ../updateboard.py -b Soccer
python ../updateboard.py -b Sociology
python ../updateboard.py -b Software
python ../updateboard.py -b Sound_of_Music
python ../updateboard.py -b Southwest
python ../updateboard.py -b SportsNews
python ../updateboard.py -b sqilaw
python ../updateboard.py -b StartUp
python ../updateboard.py -b Statistics
python ../updateboard.py -b Stock
python ../updateboard.py -b SUDA
python ../updateboard.py -b SunLaw
python ../updateboard.py -b Supershow
python ../updateboard.py -b Swimming
python ../updateboard.py -b Switzerland
python ../updateboard.py -b SWJTU
python ../updateboard.py -b sysop
python ../updateboard.py -b Taiwan
python ../updateboard.py -b talk
python ../updateboard.py -b TAX
python ../updateboard.py -b Tennessee
python ../updateboard.py -b Tennis
python ../updateboard.py -b test
python ../updateboard.py -b TeX
python ../updateboard.py -b Texas
python ../updateboard.py -b TexasHoldem
python ../updateboard.py -b TheStrait
python ../updateboard.py -b Thoughts
python ../updateboard.py -b THU
python ../updateboard.py -b Tianjin
python ../updateboard.py -b TJU
python ../updateboard.py -b TongJi
python ../updateboard.py -b TopArticle
python ../updateboard.py -b Toronto
python ../updateboard.py -b Translation
python ../updateboard.py -b Travel
python ../updateboard.py -b Tri
python ../updateboard.py -b TrustInJesus
python ../updateboard.py -b TVChinese
python ../updateboard.py -b TVGame