#!/bin/sh
python ../updateboard.py -b Macromolecules
python ../updateboard.py -b Mainland
python ../updateboard.py -b man
python ../updateboard.py -b MartialArts
python ../updateboard.py -b Maryland
python ../updateboard.py -b Mathematics
python ../updateboard.py -b ME
python ../updateboard.py -b MedicalCareer
python ../updateboard.py -b MedicalDevice
python ../updateboard.py -b Medicalpractice
python ../updateboard.py -b Medicaltech
python ../updateboard.py -b Medicine
python ../updateboard.py -b Memory
python ../updateboard.py -b Michigan
python ../updateboard.py -b MiddleSchool
python ../updateboard.py -b Midlife
python ../updateboard.py -b Military
python ../updateboard.py -b Military2
python ../updateboard.py -b Minnesota
python ../updateboard.py -b MiscNews
python ../updateboard.py -b Mississippi
python ../updateboard.py -b Missouri
python ../updateboard.py -b MitbbsApp
python ../updateboard.py -b MitbbsColumn
python ../updateboard.py -b Mitbbs_Blog
python ../updateboard.py -b mitOCEF
python ../updateboard.py -b MJ
python ../updateboard.py -b MobileDevelopment
python ../updateboard.py -b Mod_CHN_Hist
python ../updateboard.py -b Money
python ../updateboard.py -b Montreal
python ../updateboard.py -b Movie
python ../updateboard.py -b Music
python ../updateboard.py -b MusicPlayer
python ../updateboard.py -b MyActivity
python ../updateboard.py -b NanoST
python ../updateboard.py -b NBA
python ../updateboard.py -b NCAA
python ../updateboard.py -b NCEPU
python ../updateboard.py -b NCTU
python ../updateboard.py -b Nebraska
python ../updateboard.py -b NEU
python ../updateboard.py -b Neuroscience
python ../updateboard.py -b Nevada
python ../updateboard.py -b NewBBS
python ../updateboard.py -b NewJersey
python ../updateboard.py -b NewMexico
python ../updateboard.py -b NewYork
python ../updateboard.py -b NewZealand
python ../updateboard.py -b NextGeneration
python ../updateboard.py -b NJU
python ../updateboard.py -b NKU
python ../updateboard.py -b NorthEast
python ../updateboard.py -b notepad
python ../updateboard.py -b Notice
python ../updateboard.py -b NUAA
python ../updateboard.py -b Nursing
python ../updateboard.py -b NUST
python ../updateboard.py -b NWPU
python ../updateboard.py -b NWU
python ../updateboard.py -b Ohio
python ../updateboard.py -b Oklahoma
python ../updateboard.py -b Olympics
python ../updateboard.py -b OperaHouse
python ../updateboard.py -b Oregon
python ../updateboard.py -b Ottawa
python ../updateboard.py -b OUC
python ../updateboard.py -b Outdoors
python ../updateboard.py -b Overseas
python ../updateboard.py -b OverseasFocus
python ../updateboard.py -b Paint_ball
python ../updateboard.py -b paladin
python ../updateboard.py -b PalmParadise
python ../updateboard.py -b Parenting
python ../updateboard.py -b PDA
python ../updateboard.py -b PennySaver
python ../updateboard.py -b pets
python ../updateboard.py -b Pharmaceutical
python ../updateboard.py -b Pharmacy
python ../updateboard.py -b PHILADELPHIA
python ../updateboard.py -b PhotoForum
python ../updateboard.py -b PhotoGear
python ../updateboard.py -b PhotoProcessing
python ../updateboard.py -b Physics
python ../updateboard.py -b Pics
python ../updateboard.py -b Piebridge
python ../updateboard.py -b Pilot
python ../updateboard.py -b Pingpong
python ../updateboard.py -b Pittsburgh
python ../updateboard.py -b PKU
python ../updateboard.py -b Poetry
python ../updateboard.py -b PoliticalScience
python ../updateboard.py -b PopNews
python ../updateboard.py -b Postdoc
python ../updateboard.py -b Programming
python ../updateboard.py -b Prose
python ../updateboard.py -b PsychoAnalysis
python ../updateboard.py -b Psychology
python ../updateboard.py -b Purdue