#!/bin/sh
 python ../updateboard.py -b Dance
 python ../updateboard.py -b Database
 python ../updateboard.py -b DataSciences
 python ../updateboard.py -b Detective
 python ../updateboard.py -b DHU
 python ../updateboard.py -b Donation
 python ../updateboard.py -b DotNet
 python ../updateboard.py -b Dreamer
 python ../updateboard.py -b DUT
 python ../updateboard.py -b DVD
 python ../updateboard.py -b E-Sports
 python ../updateboard.py -b EB23
 python ../updateboard.py -b ebiz
 python ../updateboard.py -b ECNU
 python ../updateboard.py -b Economics
 python ../updateboard.py -b ECUST
 python ../updateboard.py -b Education
 python ../updateboard.py -b EE
 python ../updateboard.py -b EmergingNetworking
 python ../updateboard.py -b Engineering
 python ../updateboard.py -b EnglishChat
 python ../updateboard.py -b Environmental
 python ../updateboard.py -b Europe
 python ../updateboard.py -b EuropeNews
 python ../updateboard.py -b Exchange
 python ../updateboard.py -b Faculty
 python ../updateboard.py -b Family
 python ../updateboard.py -b Fashion
 python ../updateboard.py -b FDU
 python ../updateboard.py -b Fengshui
 python ../updateboard.py -b FieldHockey
 python ../updateboard.py -b Fishing
 python ../updateboard.py -b Fitness
 python ../updateboard.py -b Flash
 python ../updateboard.py -b FleaMarket
 python ../updateboard.py -b Florida
 python ../updateboard.py -b Food
 python ../updateboard.py -b Football
 python ../updateboard.py -b Fujian
 python ../updateboard.py -b fyzlaw
 python ../updateboard.py -b Gamble
 python ../updateboard.py -b Game
 python ../updateboard.py -b gardening
 python ../updateboard.py -b GenderEquality
 python ../updateboard.py -b Georgia
 python ../updateboard.py -b GeoSpace
 python ../updateboard.py -b Germany
 python ../updateboard.py -b Ghost
 python ../updateboard.py -b GiftCard
 python ../updateboard.py -b Girl
 python ../updateboard.py -b Go
 python ../updateboard.py -b Golf
 python ../updateboard.py -b Gowest
 python ../updateboard.py -b GreatPit
 python ../updateboard.py -b Guang_Xi
 python ../updateboard.py -b GunsAndGears